#!/bin/sh

command=comsol

# define all the file names
JOB_ID=001
JOB_NAME=dwt-comsol
num=001
recordname=fb-comsol-${num}.txt
logname=log-comsol-${num}.txt

# register the job
MPHNAME="$(./mkjob_comsol.py)"
COUNTER=0
while [ ! -z "$MPHNAME" ]
do
    echo "+++++++++++++++++++++++++++++++" >> ${recordname}
    date >> ${recordname}

    donefile=${MPHNAME}_Done.mph
    logfile=${MPHNAME}_Log.txt
    mphfile=${MPHNAME}.mph
    echo "${MPHNAME} to run"  >>${recordname}
    touch $donefile
    touch $logfile

    date >> ${recordname}
    echo "--------------------------------" >> ${recordname}
    MPHNAME="$(./mkjob_comsol.py)"

    # a circuit breaker to provent infinite loop
    let COUNTER=COUNTER+1 
    if [  $COUNTER -gt 1000 ]; then
	break
    fi
done
#  cleanup /tmp (if necessary)
#


